title: LAKERAVEN
email: info@lakeraven.com
description: >- # this means to ignore newlines
  Lakeraven is a Native-owned, veteran-led consultancy delivering accessible, human-centered digital services for government and tribal nations.

# Twitter handle. Only the handle, not the URL.
# twitter: agency_name

# Used to construct absolute URLs throughout the site
url: "https://lakeraven.com"

# Configuration for Google Analytics
ga:
  # ua: your-ua

# Site Navigation
primary_navigation:
  - name: Home
    url: /
#  - name: Blog
#    url: /blog/
  - name: About
    url: /about/
  - name: Services
    url: /services/
#  - name: Document with sidenav
#    url: /document-with-sidenav/
#  - name: Document submenu
#    children:
#      - name: Navigation link
#        url: "#main-content"
#      - name: Navigation link
#        url: "#main-content"
#      - name: Navigation link
#        url: "#main-content"

#secondary_navigation:
#  - name: Secondary link
#    url: "#main-content"
#  - name: Another secondary link
#    url: "#main-content"

# Search.gov configuration
#
# 1. Create an account with Search.gov https://search.usa.gov/signup
# 2. Add a new site.
# 3. Add your site/affiliate name here.


##########################################################################################
# The values below here are more advanced and should only be
# changed if you know what they do
##########################################################################################
